name: stainless-steel
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - nbformat
  - os
  # add here as you adopt them, e.g. xgboost, lightgbm
  - pip
  - pip: